<?php

/**
 * @file
 * Primary module hooks for JWT Auth API module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function jwt_auth_api_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    case 'help.page.jwt_auth_api':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Provides JWT authentication for API access.') . '</p>';
      return $output;
  }
}